ALTER TABLE signal_definition ADD COLUMN IF NOT EXISTS calibration_mode VARCHAR(30) NOT NULL DEFAULT 'LINEAR';
ALTER TABLE signal_definition ADD COLUMN IF NOT EXISTS offset DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE signal_definition ADD COLUMN IF NOT EXISTS filter_alpha DOUBLE PRECISION NOT NULL DEFAULT 1;
ALTER TABLE signal_definition ADD COLUMN IF NOT EXISTS deadband DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE signal_definition ADD COLUMN IF NOT EXISTS calibrated_at TIMESTAMPTZ;
ALTER TABLE signal_definition ADD COLUMN IF NOT EXISTS calibrated_by INTEGER;
