import csv, hashlib, io, json, zipfile
from datetime import datetime, timezone
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak

NAVY=colors.HexColor('#061522');CYAN=colors.HexColor('#00c8e8');LIME=colors.HexColor('#9dde35');MUTED=colors.HexColor('#56717e');LIGHT=colors.HexColor('#eef6f8');AMBER=colors.HexColor('#f3a51f')

def canonical_json(value):
    return json.dumps(value,sort_keys=True,separators=(',',':'),ensure_ascii=True).encode('utf-8')

def report_id(asset_id,generated_at,payload):
    stamp=generated_at.strftime('%Y%m%dT%H%M%SZ')
    digest=hashlib.sha256(canonical_json(payload)).hexdigest()[:12].upper()
    return f'AT360-EV-{asset_id}-{stamp}-{digest}'

def _styles():
    s=getSampleStyleSheet();s.add(ParagraphStyle(name='Cover',parent=s['Title'],fontName='Helvetica-Bold',fontSize=24,textColor=LIGHT,alignment=TA_CENTER,spaceAfter=10));s.add(ParagraphStyle(name='Section',parent=s['Heading2'],fontName='Helvetica-Bold',fontSize=14,textColor=NAVY,spaceBefore=10,spaceAfter=7));s.add(ParagraphStyle(name='Small',parent=s['BodyText'],fontSize=8,leading=11,textColor=MUTED));s.add(ParagraphStyle(name='Body2',parent=s['BodyText'],fontSize=9.5,leading=13));return s

def _table(rows,widths=None,header=True):
    t=Table(rows,colWidths=widths,repeatRows=1 if header else 0,hAlign='LEFT')
    style=[('GRID',(0,0),(-1,-1),.35,colors.HexColor('#b3c6ce')),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('LEFTPADDING',(0,0),(-1,-1),7),('RIGHTPADDING',(0,0),(-1,-1),7),('TOPPADDING',(0,0),(-1,-1),6),('BOTTOMPADDING',(0,0),(-1,-1),6),('FONTNAME',(0,0),(-1,-1),'Helvetica'),('FONTSIZE',(0,0),(-1,-1),8)]
    if header:style += [('BACKGROUND',(0,0),(-1,0),NAVY),('TEXTCOLOR',(0,0),(-1,0),colors.white),('FONTNAME',(0,0),(-1,0),'Helvetica-Bold')]
    for r in range(1 if header else 0,len(rows)):
        if r%2==0:style.append(('BACKGROUND',(0,r),(-1,r),colors.HexColor('#f2f7f9')))
    t.setStyle(TableStyle(style));return t

def build_pdf(payload):
    out=io.BytesIO();styles=_styles();doc=SimpleDocTemplate(out,pagesize=A4,rightMargin=18*mm,leftMargin=18*mm,topMargin=16*mm,bottomMargin=16*mm,title=payload['report_id'],author='AssetTrack 360')
    story=[]
    cover=Table([[Paragraph('ASSETTRACK 360',styles['Cover'])],[Paragraph('Evidence Report',ParagraphStyle(name='Sub',parent=styles['Cover'],fontSize=17,textColor=CYAN))],[Paragraph(payload['report_id'],ParagraphStyle(name='Rid',parent=styles['Small'],alignment=TA_CENTER,textColor=colors.white))]],colWidths=[174*mm])
    cover.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),NAVY),('TOPPADDING',(0,0),(-1,0),22),('BOTTOMPADDING',(0,-1),(-1,-1),20)]));story += [cover,Spacer(1,10*mm)]
    story += [_table([['Customer','Asset','Device UID'],[payload['customer_name'],payload['asset_name'],payload['device_uid']]],widths=[58*mm]*3),Spacer(1,5*mm)]
    story += [_table([['Report period','Generated UTC','Generated by'],[payload['period'],payload['generated_at'],payload['generated_by']]],widths=[58*mm]*3),Spacer(1,6*mm)]
    story += [Paragraph('Executive Evidence Summary',styles['Section']),_table([['Validated state','Distance','Movement time','Maximum valid speed','Trust'],[payload['state'],f"{payload['distance_km']:.2f} km",f"{payload['movement_minutes']} min",f"{payload['maximum_speed']} km/h",f"{payload['confidence']}%"]],widths=[35*mm]*5),Spacer(1,4*mm)]
    story += [Paragraph('Evidence Classification',styles['Section']),_table([['Class','Meaning'],['MEASURED','Data received directly from the registered device.'],['VALIDATED','Data accepted after identity, quality and movement checks.'],['REJECTED','Data retained for evidence but excluded from operational calculations.'],['PREDICTED','Scenario information only. Never telemetry and never an event.']],widths=[35*mm,140*mm])]
    story += [PageBreak(),Paragraph('Evidence Chain',styles['Section']),_table([['Stage','Detail','State']]+[[x['label'],x['detail'],x['state']] for x in payload['evidence']],widths=[48*mm,90*mm,37*mm])]
    story += [Paragraph('Observation Summary',styles['Section']),_table([['Raw','Validated movement','Stationary drift','Rejected'],[payload['raw_count'],payload['movement_count'],payload['drift_count'],payload['rejected_count']]],widths=[43.5*mm]*4)]
    story += [Paragraph('Device and Capability Context',styles['Section']),_table([['Firmware','Battery','Charging','Geofence zones'],[payload['firmware'],payload['battery'],payload['charging'],payload['geofence_count']]],widths=[43.5*mm]*4)]
    accepted=payload['accepted_locations'];rejected=payload['rejected_observations']
    story += [Paragraph('Validated Movement Locations',styles['Section'])]
    story.append(_table([['Timestamp UTC','Latitude','Longitude','Accuracy m','Speed km/h']]+[[x['timestamp'],x['latitude'],x['longitude'],x['accuracy'],x['speed']] for x in accepted],widths=[50*mm,34*mm,34*mm,28*mm,28*mm]) if accepted else Paragraph('No movement locations passed the movement confirmation gate.',styles['Body2']))
    story += [Paragraph('Rejected and Excluded Observations',styles['Section'])]
    observations=rejected+payload['stationary_drift']
    story.append(_table([['Timestamp UTC','Latitude','Longitude','Accuracy m','Reason']]+[[x['timestamp'],x['latitude'],x['longitude'],x['accuracy'],x.get('reason','STATIONARY_DRIFT')] for x in observations],widths=[48*mm,31*mm,31*mm,27*mm,38*mm]) if observations else Paragraph('No observations were rejected or excluded.',styles['Body2']))
    story += [Spacer(1,6*mm),Paragraph('Integrity and Use Notice',styles['Section']),Paragraph(f"Payload SHA-256: {payload['payload_sha256']}",styles['Small']),Spacer(1,2*mm),Paragraph('This report distinguishes device measurements from validated operational values. Rejected observations remain visible for fault finding. Predictions and counterfactual previews are not device telemetry, alarms or confirmed safety events. The report supports customer operations and technical review; it does not independently establish legal liability or prove a crash.',styles['Body2'])]
    def footer(canvas,doc):
        canvas.saveState();canvas.setFont('Helvetica',7);canvas.setFillColor(MUTED);canvas.drawString(18*mm,10*mm,payload['report_id']);canvas.drawRightString(192*mm,10*mm,f'Page {doc.page}');canvas.restoreState()
    doc.build(story,onFirstPage=footer,onLaterPages=footer);return out.getvalue()

def _csv_bytes(rows,fields):
    text=io.StringIO();w=csv.DictWriter(text,fieldnames=fields,extrasaction='ignore');w.writeheader();w.writerows(rows);return text.getvalue().encode('utf-8')

def build_pack(payload):
    files={}
    files['Evidence_Report.pdf']=build_pdf(payload)
    files['Evidence_Summary.json']=json.dumps(payload,indent=2,sort_keys=True,ensure_ascii=True).encode('utf-8')
    files['Accepted_Locations.csv']=_csv_bytes(payload['accepted_locations'],['timestamp','latitude','longitude','accuracy','speed'])
    files['Rejected_Observations.csv']=_csv_bytes(payload['rejected_observations']+payload['stationary_drift'],['timestamp','latitude','longitude','accuracy','speed','reason'])
    files['Safety_Events.csv']=_csv_bytes(payload['safety_events'],['timestamp','event_type','severity','status','confidence'])
    files['Device_Status.json']=json.dumps(payload['device_status'],indent=2,sort_keys=True).encode('utf-8')
    files['Geofence_Definition.json']=json.dumps(payload['geofences'],indent=2,sort_keys=True).encode('utf-8')
    manifest=['ASSETTRACK 360 EVIDENCE INTEGRITY MANIFEST',payload['report_id'],'']
    for name,data in sorted(files.items()):manifest.append(f"{hashlib.sha256(data).hexdigest()}  {name}")
    files['Integrity_Manifest.txt']='\n'.join(manifest).encode('utf-8')
    out=io.BytesIO()
    with zipfile.ZipFile(out,'w',zipfile.ZIP_DEFLATED) as z:
        for name,data in files.items():z.writestr(name,data)
    return out.getvalue()
