from ..schema import health_channel

PROFILE = {
    "code": "AT360_LILYGO_T_SIM7000G",
    "display_name": "LILYGO T-SIM7000G",
    "device_type": "LILYGO_T_SIM7000G_TRACKER",
    "asset_type": "TRACKER",
    "transport": "CELLULAR_WIFI",
    "firmware_family": "AT360_LILYGO_T_SIM7000G",
    "revision_state": "UNVERIFIED_AUTO_DETECT",
    "capabilities": [
        "WIFI", "BLE", "LTE_CAT_M1", "NB_IOT", "GPRS_FALLBACK", "GNSS",
        "BATTERY_MONITOR", "SOLAR_MONITOR", "OPTIONAL_MICROSD", "OFFLINE_QUEUE",
        "SIMULATION", "REVISION_LOCKED_CUSTOM_IO",
    ],
    "channels": [
        health_channel("gps_fix", "GNSS Fix", "STATE", "TSIM7000G"),
        health_channel("speed_kmh", "Speed", "SPEED", "TSIM7000G", "km/h", "numeric"),
        health_channel("heading", "Heading", "HEADING", "TSIM7000G", "deg", "numeric"),
        health_channel("satellites", "Satellites", "COUNT", "TSIM7000G", "sat", "numeric"),
        health_channel("battery_v", "Battery Voltage", "VOLTAGE", "TSIM7000G", "V", "battery"),
        health_channel("battery_percent", "Battery", "PERCENT", "TSIM7000G", "%", "battery"),
        health_channel("charging_status", "Charging Status", "STATE", "TSIM7000G"),
        health_channel("solar_v", "Solar Input", "VOLTAGE", "TSIM7000G", "V", "numeric"),
        health_channel("cellular_signal", "Cellular Signal", "SIGNAL", "TSIM7000G", "CSQ", "numeric"),
        health_channel("network_registered", "Network Registered", "STATE", "TSIM7000G"),
        health_channel("network_mode", "Network Mode", "STATE", "TSIM7000G"),
        health_channel("wifi_rssi", "Wi-Fi Signal", "SIGNAL", "TSIM7000G", "dBm", "numeric"),
        health_channel("queue_depth", "Offline Queue Depth", "COUNT", "TSIM7000G", "points", "numeric"),
        health_channel("sd_status", "microSD Status", "STATE", "TSIM7000G"),
        health_channel("simulation_mode", "Simulation Mode", "STATE", "TSIM7000G"),
    ],
    "output_channels": [],
    "reserved_pins": [
        {"pin": "GPIO27", "purpose": "SIM7000G UART TX", "customer_output": False},
        {"pin": "GPIO26", "purpose": "SIM7000G UART RX", "customer_output": False},
        {"pin": "GPIO4", "purpose": "SIM7000G PWR KEY", "customer_output": False},
        {"pin": "GPIO25", "purpose": "SIM7000G DTR", "customer_output": False},
        {"pin": "GPIO35", "purpose": "Battery ADC input-only", "customer_output": False},
        {"pin": "GPIO36", "purpose": "Solar ADC input-only", "customer_output": False},
        {"pin": "GPIO12", "purpose": "Onboard LED", "customer_output": False},
        {"pin": "GPIO2", "purpose": "Optional microSD MISO", "customer_output": False},
        {"pin": "GPIO13", "purpose": "Optional microSD CS", "customer_output": False},
        {"pin": "GPIO14", "purpose": "Optional microSD CLK", "customer_output": False},
        {"pin": "GPIO15", "purpose": "Optional microSD MOSI", "customer_output": False},
    ],
    "board_metadata": {
        "board_family": "LILYGO T-SIM7000G",
        "mcu": "ESP32-WROVER-B",
        "modem": "SIM7000G",
        "revision": "UNVERIFIED",
        "micro_sd": "OPTIONAL_DEFAULT_OFF",
        "customer_io": "LOCKED_PENDING_PHYSICAL_REVISION_VALIDATION",
        "local_setup": "Permanent AP and local web portal",
    },
    "profile_notice": "Revision-safe tracker profile. Cellular, GNSS, battery, solar, Wi-Fi and optional microSD are enabled. Customer GPIO remains locked until the physical PCB revision is verified.",
}
