from ..schema import analog_channel, input_channel, output_feedback

PROFILE = {
    "code": "AT360_ESP32D_EXPANDED",
    "display_name": "ESP32-D 38-pin Expanded Remote I/O",
    "device_type": "ESP32D_38PIN_REMOTE_IO",
    "asset_type": "GENERIC",
    "transport": "WIFI",
    "firmware_family": "AT360_ESP32D_38PIN",
    "capabilities": [
        "WIFI",
        "BLE",
        "ANALOG_INPUT_1",
        "ANALOG_INPUT_2",
        "ANALOG_INPUT_3",
        "ANALOG_INPUT_4",
        "DIGITAL_INPUT_1",
        "DIGITAL_INPUT_2",
        "DIGITAL_INPUT_3",
        "DIGITAL_INPUT_4",
        "PULSE_COUNTER_1",
        "PULSE_COUNTER_2",
        "DIGITAL_OUTPUT_1",
        "DIGITAL_OUTPUT_2",
        "DIGITAL_OUTPUT_3",
        "DIGITAL_OUTPUT_4",
        "LOCAL_ARM",
        "OUTPUT_LATCHED",
        "OUTPUT_PULSE",
        "SIMULATION_MODE",
        "WIFI_RSSI",
    ],
    "channels": [
        {
            **analog_channel("analog_1", "Analog Input 1", "ESP32D"),
            "pin": "GPIO34",
            "pin_notes": "ADC1 input-only; protected 0-3.3 V maximum",
        },
        {
            "key": "analog_1_volts",
            "label": "Analog Input 1 Voltage",
            "signal_type": "VOLTAGE",
            "source_type": "ESP32D",
            "unit": "V",
            "widget": "numeric",
            "direction": "HEALTH",
            "calibratable": False,
            "pin": "GPIO34",
        },
        {
            **analog_channel("analog_2", "Analog Input 2", "ESP32D"),
            "pin": "GPIO35",
            "pin_notes": "ADC1 input-only; protected 0-3.3 V maximum",
        },
        {
            "key": "analog_2_volts",
            "label": "Analog Input 2 Voltage",
            "signal_type": "VOLTAGE",
            "source_type": "ESP32D",
            "unit": "V",
            "widget": "numeric",
            "direction": "HEALTH",
            "calibratable": False,
            "pin": "GPIO35",
        },
        {
            **analog_channel("analog_3", "Analog Input 3", "ESP32D"),
            "pin": "GPIO36",
            "pin_notes": "ADC1 input-only; protected 0-3.3 V maximum",
        },
        {
            "key": "analog_3_volts",
            "label": "Analog Input 3 Voltage",
            "signal_type": "VOLTAGE",
            "source_type": "ESP32D",
            "unit": "V",
            "widget": "numeric",
            "direction": "HEALTH",
            "calibratable": False,
            "pin": "GPIO36",
        },
        {
            **analog_channel("analog_4", "Analog Input 4", "ESP32D"),
            "pin": "GPIO39",
            "pin_notes": "ADC1 input-only; protected 0-3.3 V maximum",
        },
        {
            "key": "analog_4_volts",
            "label": "Analog Input 4 Voltage",
            "signal_type": "VOLTAGE",
            "source_type": "ESP32D",
            "unit": "V",
            "widget": "numeric",
            "direction": "HEALTH",
            "calibratable": False,
            "pin": "GPIO39",
        },
        {
            **input_channel("digital_1", "Digital Input 1", "STATE", "ESP32D"),
            "pin": "GPIO4",
            "active_level": "LOW",
        },
        {
            **input_channel("digital_2", "Digital Input 2", "STATE", "ESP32D"),
            "pin": "GPIO13",
            "active_level": "LOW",
        },
        {
            **input_channel("digital_3", "Digital Input 3", "STATE", "ESP32D"),
            "pin": "GPIO18",
            "active_level": "LOW",
        },
        {
            **input_channel("digital_4", "Digital Input 4", "STATE", "ESP32D"),
            "pin": "GPIO19",
            "active_level": "LOW",
        },
        {
            **input_channel("pulse_1_count", "Pulse Counter 1", "COUNT", "ESP32D", "pulses", "numeric"),
            "pin": "GPIO26",
            "edge": "FALLING",
        },
        {
            **input_channel("pulse_2_count", "Pulse Counter 2", "COUNT", "ESP32D", "pulses", "numeric"),
            "pin": "GPIO27",
            "edge": "FALLING",
        },
        {
            **input_channel("local_arm_status", "Local Arm Status", "STATE", "ESP32D"),
            "pin": "GPIO32",
            "active_level": "LOW",
            "safety_interlock": True,
        },
        {
            **output_feedback("digital_output_1_feedback", "Digital Output 1 Feedback", "ESP32D", "DO1"),
            "pin": "GPIO25",
        },
        {
            **output_feedback("digital_output_2_feedback", "Digital Output 2 Feedback", "ESP32D", "DO2"),
            "pin": "GPIO21",
        },
        {
            **output_feedback("digital_output_3_feedback", "Digital Output 3 Feedback", "ESP32D", "DO3"),
            "pin": "GPIO22",
        },
        {
            **output_feedback("digital_output_4_feedback", "Digital Output 4 Feedback", "ESP32D", "DO4"),
            "pin": "GPIO23",
        },
        {
            "key": "wifi_rssi",
            "label": "Wi-Fi Signal",
            "signal_type": "SIGNAL",
            "source_type": "ESP32D",
            "unit": "dBm",
            "widget": "numeric",
            "direction": "HEALTH",
            "calibratable": False,
        },
        {
            "key": "simulation_mode",
            "label": "Simulation Mode",
            "signal_type": "STATE",
            "source_type": "ESP32D",
            "unit": "",
            "widget": "state",
            "direction": "HEALTH",
            "calibratable": False,
        },
    ],
    "output_channels": [
        {
            "channel": "DO1",
            "label": "Digital Output 1",
            "mode": "LATCHED_OR_PULSE",
            "default_mode": "LATCHED",
            "pulse_seconds": 1,
            "supported_actions": ["OUTPUT_ON", "OUTPUT_OFF", "OUTPUT_PULSE"],
            "requires_local_arm": True,
            "safe_boot_state": "OFF",
            "simulation_physical_lockout": True,
            "feedback_key": "digital_output_1_feedback",
            "pin": "GPIO25",
        },
        {
            "channel": "DO2",
            "label": "Digital Output 2",
            "mode": "LATCHED_OR_PULSE",
            "default_mode": "LATCHED",
            "pulse_seconds": 1,
            "supported_actions": ["OUTPUT_ON", "OUTPUT_OFF", "OUTPUT_PULSE"],
            "requires_local_arm": True,
            "safe_boot_state": "OFF",
            "simulation_physical_lockout": True,
            "feedback_key": "digital_output_2_feedback",
            "pin": "GPIO21",
        },
        {
            "channel": "DO3",
            "label": "Digital Output 3",
            "mode": "LATCHED_OR_PULSE",
            "default_mode": "LATCHED",
            "pulse_seconds": 1,
            "supported_actions": ["OUTPUT_ON", "OUTPUT_OFF", "OUTPUT_PULSE"],
            "requires_local_arm": True,
            "safe_boot_state": "OFF",
            "simulation_physical_lockout": True,
            "feedback_key": "digital_output_3_feedback",
            "pin": "GPIO22",
        },
        {
            "channel": "DO4",
            "label": "Digital Output 4",
            "mode": "LATCHED_OR_PULSE",
            "default_mode": "LATCHED",
            "pulse_seconds": 1,
            "supported_actions": ["OUTPUT_ON", "OUTPUT_OFF", "OUTPUT_PULSE"],
            "requires_local_arm": True,
            "safe_boot_state": "OFF",
            "simulation_physical_lockout": True,
            "feedback_key": "digital_output_4_feedback",
            "pin": "GPIO23",
        },
    ],
    "board_metadata": {
        "board_family": "ESP32-D 38-pin",
        "wifi_status_led": "GPIO33",
        "local_arm_pin": "GPIO32",
        "analog_input_count": 4,
        "digital_input_count": 4,
        "pulse_input_count": 2,
        "digital_output_count": 4,
    },
}
